version: '3'

services:
  proxy:
    ports:
      - "8080:80"
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: proxy
    networks: 
      - eps364
    depends_on: 
      - app

  app:
    build: 
      context: ./node
      dockerfile: Dockerfile
    image: app
    working_dir: /home/node/app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: sh -c "npm start"
    depends_on: 
      - db
    networks: 
      - eps364

  db:
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - .data/bd:/var/lib/mysql:rw
      - ./mysql/db:/docker-entrypoint-initdb.d:rw
    ports:
      - "3306:3306"
    networks: 
      - eps364

networks: 
  eps364:
    driver: bridge
